// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-XT61tiGv7YLhik-6KFq5V6gpyvQnZBw',
    appId: '1:989404866502:web:93bf1662f1d4b20621b4c7',
    messagingSenderId: '989404866502',
    projectId: 'equity-6d8c4',
    authDomain: 'equity-6d8c4.firebaseapp.com',
    storageBucket: 'equity-6d8c4.firebasestorage.app',
    measurementId: 'G-M3M9EDW1DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnbrWWAgQToZGBS_IwdRVyNvAbbVVkZlg',
    appId: '1:989404866502:android:493bdb5a85a3717621b4c7',
    messagingSenderId: '989404866502',
    projectId: 'equity-6d8c4',
    storageBucket: 'equity-6d8c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd86G5aNOKVaepgslwzddGpiB96ydU7mY',
    appId: '1:989404866502:ios:2c61eb1399702c7f21b4c7',
    messagingSenderId: '989404866502',
    projectId: 'equity-6d8c4',
    storageBucket: 'equity-6d8c4.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd86G5aNOKVaepgslwzddGpiB96ydU7mY',
    appId: '1:989404866502:ios:2c61eb1399702c7f21b4c7',
    messagingSenderId: '989404866502',
    projectId: 'equity-6d8c4',
    storageBucket: 'equity-6d8c4.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-XT61tiGv7YLhik-6KFq5V6gpyvQnZBw',
    appId: '1:989404866502:web:9f9db2753079f4b821b4c7',
    messagingSenderId: '989404866502',
    projectId: 'equity-6d8c4',
    authDomain: 'equity-6d8c4.firebaseapp.com',
    storageBucket: 'equity-6d8c4.firebasestorage.app',
    measurementId: 'G-TE96LS3VYB',
  );
}
